steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA', '--network=cloudbuild', '.', '--progress=plain']

# Push the Docker image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA']

# Deploy the image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - ${_SERVICE_NAME}
    - --project=${_PROJECT}
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated
    - --cpu=${_CPU}
    - --cpu-boost
    - --execution-environment=gen2
    - --memory=${_MEMORY}
    - --service-account=${_SERVICE_ACCOUNT}
    - --image=${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA
    - --port=11434

options:
  logging: CLOUD_LOGGING_ONLY